environment:
  matrix:
  - TARGET: x86_64-pc-windows-gnu
    VERSION: nightly
  - TARGET: i686-pc-windows-gnu
    VERSION: nightly
  - TARGET: x86_64-pc-windows-gnu
    VERSION: 1.1.0
  - TARGET: i686-pc-windows-gnu
    VERSION: 1.1.0
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:VERSION}-${env:TARGET}.exe"
  - rust-%VERSION%-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --verbose
